version: '2'
services:
    trungico-app:
        image: trungico
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://trungico-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=trungico
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trungico-mongodb:
        extends:
            file: mongodb.yml
            service: trungico-mongodb
